version: "3.3"
services:
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27100:27017"
    volumes:
      - ./data/dev/mongo:/data/db
    networks:
      - network-mongo

networks:
  network-mongo:
    driver: bridge